import streamlit as st
import os
from main import graph  # Import your compiled LangGraph instance
import re
import glob

# Set up page configurations for a spacious dashboard layout
st.set_page_config(page_title="Agentic PPTX Studio", layout="wide", initial_sidebar_state="expanded")

# Apply custom dark slate styling to match your backend design aesthetics
st.markdown("""
    <style>
    .reportview-container { background: #020617; }
    .stCard { background-color: #0f172a; border: 1px solid #1e293b; padding: 20px; border-radius: 12px; }
    </style>
""", unsafe_allow_html=True)

st.title("🎨 Agentic Presentation & Slide Studio")
st.caption("Structured multi-agent pipeline powered by LangGraph & Playwright")

# --- SIDEBAR CONFIGURATIONS ---
with st.sidebar:
    st.header("⚙️ Pipeline Configurations")
    
    # Let users select their canvas style dynamically
    bg_style = st.selectbox("Canvas Background Pattern", ["tech_grid", "minimal_dark", "solid_slate"])
    
    st.subheader("🎨 Brand Theme Overrides")
    accent_color = st.color_picker("Accent Highlight Color", "#38bdf8")
    primary_color = st.color_picker("Primary Font Color", "#f8fafc")
    
    st.markdown("---")
    st.markdown("### 📄 Source Document")
    uploaded_file = st.file_uploader("Upload Raw Markdown Content Source", type=["md", "txt"])

# --- MAIN CONTENT AREA ---
col_input, col_output = st.columns([1, 2])

with col_input:
    st.subheader("🚀 Execution Controller")
    
    if uploaded_file is not None:
        # Read the file data into a string variable in live memory
        raw_markdown_text = uploaded_file.read().decode("utf-8")
        st.success("✔ Markdown text loaded into memory!")
        
        # Display a quick code-preview snippet of what was uploaded
        with st.expander("Preview Uploaded Text Content"):
            st.code(raw_markdown_text[:500] + "...", language="markdown")
        
        # Trigger button to pass the string payload to LangGraph
        if st.button("▶ Run Agentic Pipeline", type="primary", use_container_width=True):
            
            # Formulate the EXACT state dictionary expected by your graph schema
            initial_input = {
                "raw_file_content": raw_markdown_text,
                "design_config": {
                    "bg_canvas": "#020617",
                    "primary": "#f8fafc",
                    "secondary": "#94a3b8",
                    "accent": "#38bdf8",
                    "background_style": "tech_grid"
                }
            }
            
            status_box = st.empty()
            
            try:
                status_box.info("⏳ Processing your markdown through the agent graph...")
                
                # Run the stream processing loop to track state updates live
                for chunk in graph.stream(initial_input):
                    for node_name, output in chunk.items():
                        status_box.markdown(f"⚙️ **Active Agent Node:** `[{node_name}]` is executing...")
                
                status_box.success("🎉 Slide Deck generation complete!")
                st.rerun()  # Forces a UI refresh to load newly generated screenshots
                
            except Exception as e:
                st.error(f"❌ Pipeline Execution Error: {str(e)}")
    else:
        st.info("💡 Please upload a markdown document in the sidebar to start the pipeline.")
            # Stream graph updates node-by-node
           
with col_output:
    st.subheader("🖼 Generated Slide Deck Frames")
    
    # Dynamically scan local workspace for screenshots generated by your slide_renderer_node
    raw_images = glob.glob("slide_deck_page_*.png")

    # 2. Sort using a regex key that extracts the number as an integer
    rendered_images = sorted(raw_images, key=lambda x: int(re.search(r'\d+', x).group()))
    
    
    if rendered_images:
        # Layout preview slides cleanly inside a 2-column image viewport grid
        img_grid = st.columns(1)
        for idx, img_path in enumerate(rendered_images):
            print(img_path)
            with img_grid[idx % 1]:
                st.image(img_path, caption=f"Slide Frame {idx + 1:02d}", use_container_width=True)
                
        # Expose a clean, targeted download button for the compiled output binary PowerPoint layout
        if os.path.exists("Final_Presentation.pptx"):
            with open("Final_Presentation.pptx", "rb") as pptx_file:
                st.download_button(
                    label="📥 Download Production PPTX Deck",
                    data=pptx_file,
                    file_name="Generated_Executive_Deck.pptx",
                    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    use_container_width=True
                )
    else:
        st.markdown(
            "<div style='border: 2px dashed #1e293b; padding: 40px; text-align: center; border-radius: 12px; color: #64748b;'>"
            "No compiled asset canvases detected. Initialize execution pipeline to render slide matrix slices."
            "</div>", 
            unsafe_allow_html=True
        )